BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ' || 'MU_INCONSISTENCIAS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "MU_INCONSISTENCIAS"
   (	"REPORT_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(400 BYTE) NOT NULL ENABLE,
	"CUSTOM_INDEX" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"EXPECTED" VARCHAR2(100 BYTE),
	"REPORT_ENABLED" NUMBER NOT NULL ENABLE,
	"REPORT_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 CONSTRAINT "MU_INCONSISTENCIAS" PRIMARY KEY ("REPORT_ID")
  );
