create or replace PROCEDURE MU_DATA(Report_name IN VARCHAR, Description IN VARCHAR, Result IN NUMBER,
Enabled IN NUMBER, EXEC_BEGIN IN DATE, EXEC_END IN DATE, EXPECTED IN VARCHAR) IS

BEGIN

	INSERT INTO MU_RESULTS (REPORT_NAME, DESCRIPTION, RESULT, ENABLED, EXEC_BEGIN, EXEC_END, EXPECTED)
    VALUES (Report_name, Description, Result, Enabled, EXEC_BEGIN, EXEC_END, EXPECTED);
	COMMIT;

END MU_DATA;
/

-- GRANTS
