BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ' || 'REPORTES_INCONSISTENCIAS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "REPORTES_INCONSISTENCIAS" 
   (	"REPORT_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"CUSTOM_INDEX" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SUBGROUP" VARCHAR2(100 BYTE),
	"EXPECTED" VARCHAR2(20 BYTE), 
	"REPORT_ENABLED" NUMBER NOT NULL ENABLE, 
	"REPORT_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,  
	 CONSTRAINT "REPORTES_INCONSISTENCIAS_PK" PRIMARY KEY ("REPORT_ID")
  );
 
