BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ' || 'TB_INCONSISTENCIAS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_INCONSISTENCIAS" 
	(	"REPORT_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"RESULT" VARCHAR2(20 BYTE),
	"EXPECTED" VARCHAR2(20 BYTE), 
	"EXEC_BEGIN" DATE NOT NULL ENABLE, 
	"EXEC_END" DATE NOT NULL ENABLE,	
	"ENABLED" NUMBER NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(200 BYTE)
	);

-- GRANTS