create or replace PROCEDURE REGLETAS_INCONS
AS

result number;
exec_begin DATE;
exec_end DATE;

    CURSOR INCO IS
        select * from REPORTES_INCONSISTENCIAS where SUBGROUP='REGLETAS' order by REPORT_ID;

BEGIN

    FOR reg IN INCO
    LOOP

    if reg.REPORT_ID = 'REGLETAS DUPLICADAS' and reg.REPORT_ENABLED = 1 then
        BEGIN
            select SYSDATE into exec_BEGIN from dual;
        END;

        BEGIN
            SELECT COUNT(*) INTO RESULT FROM(
                SELECT LNODO.LINKVALUE AS NODO, LBAS.LINKVALUE AS BASTIDOR, LPAT.LINKVALUE AS PATCHERA, CONCAT.LINKVALUE AS CONCAT, COUNT(*) AS CANTIDAD
                FROM SPROBJECTS O, SPRLINKS LNODO, SPRLINKS LBAS, SPRLINKS LPAT, SPRLINKS CONCAT
                WHERE O.SPRID = 192 AND O.LOGIDTO = 0
                AND   LNODO.OBJECTID = O.OBJECTID AND LNODO.LINKID = 243 AND LNODO.LOGIDTO = 0
                AND   LBAS.OBJECTID  = O.OBJECTID AND LBAS.LINKID  = 11  AND LBAS.LOGIDTO = 0
                AND   LPAT.OBJECTID  = O.OBJECTID AND LPAT.LINKID  = 386 AND LPAT.LOGIDTO = 0
                AND   CONCAT.OBJECTID  = O.OBJECTID AND CONCAT.LINKID  = 442 AND CONCAT.LOGIDTO = 0
                GROUP BY LNODO.LINKVALUE, LBAS.LINKVALUE, LPAT.LINKVALUE, CONCAT.LINKVALUE
                HAVING COUNT(*) > 1
                ORDER BY LNODO.LINKVALUE, LBAS.LINKVALUE, LPAT.LINKVALUE, CONCAT.LINKVALUE);
        END;

        BEGIN
            select SYSDATE into exec_end from dual;
        END;
    end if;

        RESULT_REPORT(reg.REPORT_ID, reg.DESCRIPTION, RESULT, reg.REPORT_ENABLED, EXEC_BEGIN, EXEC_END, reg.EXPECTED);
    END LOOP;
    COMMIT;

END REGLETAS_INCONS;
/